2025-05-13 10:21:07,656 - __main__ - INFO - Environment setup complete
2025-05-13 10:21:07,657 - __main__ - ERROR - Error starting application: No module named 'ui'
Traceback (most recent call last):
  File "c:\Users\AAbdesselam\OneDrive - Scientific Network South Tyrol\Research & Development\Phase 1- Knowledge Elicitation and Representation\Elicit\app\main.py", line 55, in main
    from ui.main_window import MainWindow
ModuleNotFoundError: No module named 'ui'
2025-05-13 10:47:04,997 - __main__ - INFO - Environment setup complete
2025-05-13 10:47:05,171 - services.storage_service - INFO - Loaded collection with 2 rules
2025-05-13 10:47:05,171 - services.storage_service - INFO - Storage service initialized successfully
2025-05-13 10:47:05,503 - ui.main_window - INFO - Main window initialized
2025-05-13 10:47:05,627 - __main__ - INFO - Application started successfully
